name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'V*'  # Trigger workflow on versioned tags like v1.0.0
  pull_request:
    branches:
      - main
  release:
    types: [created]  # Triggers when a GitHub release is created manually

permissions:
  contents: write  # Allows GitHub Actions to upload assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Run fmt check
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')  # Only run if a versioned tag is pushed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure all tags are available

      - name: Get latest tag
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create GitHub Release (if missing)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Automated release" || echo "Release already exists"

      - name: Build release binary
        run: cargo build --release

      - name: Upload release binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$TAG_NAME" ./target/release/rsfetch --clobber
