name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]  # Triggers only when a new release is created

permissions:
  contents: write  # Allows uploading assets with GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test

      - name: Run fmt check
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy -- -D warnings

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Debug GitHub Event
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Release Tag: ${{ github.event.release.tag_name }}"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure all tags are available

      - name: Get latest tag
        id: get_tag
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Verify Tag
        run: |
          echo "Detected tag: $TAG_NAME"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Upload release binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$TAG_NAME" ./target/release/rsfetch --clobber
